name: 'Main'

on:
  push:
    tags: ['*']
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '25 12 * * 3'
  workflow_dispatch:

permissions: {}

jobs:

  lint:
    name: 'Lint'
    runs-on: 'ubuntu-20.04'
    permissions:
      contents: 'read'
    env:
      NODE_VERSION: 'lts/*'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
      - name: 'Use Node.js ${{ env.NODE_VERSION }}'
        uses: 'actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93'
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Lint'
        run: 'npm run lint'

  docs:
    name: 'Docs'
    needs: ['lint']
    runs-on: 'ubuntu-20.04'
    permissions:
      contents: 'read'
    env:
      NODE_VERSION: 'lts/*'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
      - name: 'Use Node.js ${{ env.NODE_VERSION }}'
        uses: 'actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93'
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Docs'
        run: 'npm run docs'

  build-node:
    name: 'Build and test on Node.js ${{ matrix.node_version }}'
    needs: ['lint']
    runs-on: 'ubuntu-20.04'
    permissions:
      contents: 'read'
    strategy:
      fail-fast: false
      matrix:
        node_version: ['14', '16', '18']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
      - name: 'Use Node.js ${{ matrix.node_version }}'
        uses: 'actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93'
        with:
          node-version: '${{ matrix.node_version }}'
          cache: 'npm'
      - name: 'Upgrade npm CLI'
        run: 'npm install -g npm@latest'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Build'
        run: 'npm run types && npm run build'
      - name: 'Test'
        run: 'npm run test:node'


  publish-npm:
    name: 'Publish npm package'
    needs:
      - 'build-node'
      - 'build-deno'
      - 'build-browser'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    env:
      NODE_VERSION: 'lts/*'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
      - name: 'Use Node.js ${{ env.NODE_VERSION }}'
        uses: 'actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93'
        with:
          node-version: '${{ env.NODE_VERSION }}'
          registry-url: 'https://registry.npmjs.org'
      - name: 'Publish package'
        env:
          NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
        run: |
          PKG_NAME="$(jq -r '.name' ./package.json)"; PKG_VERSION="$(jq -r '.version' ./package.json)"
          if [ "$(npm view "${PKG_NAME:?}" versions --json | jq -r --arg v "${PKG_VERSION:?}" 'index($v)')" = 'null' ]; then
            npm publish
          fi

  release-github:
    name: 'Create GitHub release'
    needs:
      - 'build-node'
      - 'build-deno'
      - 'build-browser'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    steps:
      - name: 'Create release'
        env:
          GITHUB_PAT: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          RELEASE_STATUS="$(curl -fs --proto '=https' --tlsv1.3 --globoff \
            --url "https://api.github.com/repos/${GITHUB_REPOSITORY:?}/releases/tags/${GITHUB_REF_NAME:?}" \
            --header "Authorization: Bearer ${GITHUB_PAT:?}" \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --write-out '%{http_code}' --output /dev/null ||:)"
          if [ "${RELEASE_STATUS:?}" = '200' ]; then exit 0; fi
          RELEASE_ID="$(curl -fsS --proto '=https' --tlsv1.3 --globoff \
            --url "https://api.github.com/repos/${GITHUB_REPOSITORY:?}/releases" \
            --header "Authorization: Bearer ${GITHUB_PAT:?}" \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --data "$(jq -rn --arg tag "${GITHUB_REF_NAME:?}" '{"name": $tag, "tag_name": $tag, "generate_release_notes": true}')" | jq -r '.id')"
          if [ -z "${RELEASE_ID-}" ] || [ "${RELEASE_ID:?}" = 'null' ]; then exit 1; fi
